const jobs = [
  {
    id: 1,
    title: "Front-End Web Developer",
    company: "Tech Solutions Inc.",
    salary: "$80,000 - $100,000",
    location: "New York, NY",
    jobType: "Full-time",
    category: "Web Development",
    level: "Mid-Senior Level",
    description: "We are looking for a skilled Front-End Web Developer to join our team. You will be responsible for developing and maintaining the client-side of our web applications.",
    technicalSkills: ["HTML", "CSS", "JavaScript", "ReactJS", "Redux", "Git"],
    image: "https://www.svgrepo.com/show/493549/front-end.svg"
  },
  {
    id: 2,
    title: "Back-End Developer",
    company: "Innovate Technologies",
    salary: "$90,000 - $120,000",
    location: "San Francisco, CA",
    jobType: "Full-time",
    category: "Backend Development",
    level: "Mid-Senior Level",
    description: "We are seeking a Back-End Developer to build and maintain the server-side logic and databases for our applications.",
    technicalSkills: ["Node.js", "Express.js", "Python", "Django", "MongoDB", "SQL"],
    image: "https://www.svgrepo.com/show/511496/backend-development.svg"
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "Creative Designs Co.",
    salary: "$70,000 - $95,000",
    location: "Los Angeles, CA",
    jobType: "Full-time",
    category: "Design",
    level: "Mid-Level",
    description: "Join our creative team as a UI/UX Designer and help us create user-friendly and engaging interfaces for our digital products.",
    technicalSkills: ["Figma", "Sketch", "Adobe XD", "User Research", "Wireframing"],
    image: "https://www.svgrepo.com/show/508643/ui-ux-design.svg"
  },
  {
    id: 4,
    title: "Data Scientist",
    company: "Analytics Solutions Ltd.",
    salary: "$100,000 - $140,000",
    location: "Chicago, IL",
    jobType: "Full-time",
    category: "Data Science",
    level: "Senior Level",
    description: "We are hiring a Data Scientist to analyze large datasets, develop machine learning models, and provide insights to drive business decisions.",
    technicalSkills: ["Python", "R", "Machine Learning", "Data Analysis", "SQL", "Tableau"],
    image: "https://www.svgrepo.com/show/487556/data-science-01.svg"
  },
  {
    id: 5,
    title: "Mobile App Developer (iOS)",
    company: "Mobile Innovators Inc.",
    salary: "$85,000 - $110,000",
    location: "Seattle, WA",
    jobType: "Full-time",
    category: "Mobile Development",
    level: "Mid-Level",
    description: "Become a Mobile App Developer specializing in iOS and contribute to the development of our innovative mobile applications.",
    technicalSkills: ["Swift", "Objective-C", "iOS SDK", "Xcode", "Mobile UI/UX"],
    image: "https://www.svgrepo.com/show/438997/ios.svg"
  },
  {
    id: 6,
    title: "Cybersecurity Analyst",
    company: "Secure Systems Corp.",
    salary: "$95,000 - $130,000",
    location: "Washington, D.C.",
    jobType: "Full-time",
    category: "IT Security",
    level: "Senior Level",
    description: "Join our cybersecurity team as an Analyst and protect our organization's systems and data from cyber threats.",
    technicalSkills: ["Network Security", "Intrusion Detection", "Security Auditing", "Ethical Hacking", "SIEM"],
    image: "https://www.svgrepo.com/show/479875/cyber-security-firewall.svg"
  },
  {
    id: 7,
    title: "Cloud Solutions Architect",
    company: "Cloud Services Group",
    salary: "$110,000 - $150,000",
    location: "Austin, TX",
    jobType: "Full-time",
    category: "Cloud Computing",
    level: "Senior Level",
    description: "We are looking for a Cloud Solutions Architect to design, implement, and manage our cloud infrastructure and solutions.",
    technicalSkills: ["AWS", "Azure", "Google Cloud", "Cloud Architecture", "DevOps", "Kubernetes"],
    image: "https://www.svgrepo.com/show/479870/cloud-computing-28.svg"
  },
  {
    id: 8,
    title: "AI/Machine Learning Engineer",
    company: "Artificial Intelligence Inc.",
    salary: "$120,000 - $160,000",
    location: "Boston, MA",
    jobType: "Full-time",
    category: "Artificial Intelligence",
    level: "Senior Level",
    description: "Develop cutting-edge AI and machine learning models and algorithms as an AI/Machine Learning Engineer in our innovative company.",
    technicalSkills: ["Python", "TensorFlow", "PyTorch", "Machine Learning", "Deep Learning", "NLP"],
    image: "https://www.svgrepo.com/show/487557/data-science-02.svg"
  },
  {
    id: 9,
    title: "DevOps Engineer",
    company: "Streamline Operations Ltd.",
    salary: "$105,000 - $145,000",
    location: "Denver, CO",
    jobType: "Full-time",
    category: "DevOps",
    level: "Mid-Senior Level",
    description: "Join our team as a DevOps Engineer to automate and streamline our software development and deployment processes.",
    technicalSkills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform", "Ansible"],
    image: "https://www.svgrepo.com/show/487707/devops-01.svg"
  },
  {
    id: 10,
    title: "QA Automation Engineer",
    company: "Quality First Software",
    salary: "$80,000 - $110,000",
    location: "Atlanta, GA",
    jobType: "Full-time",
    category: "Quality Assurance",
    level: "Mid-Level",
    description: "We are seeking a QA Automation Engineer to design and implement automated tests to ensure the quality of our software products.",
    technicalSkills: ["Selenium", "Cypress", "JUnit", "TestNG", "Jenkins", "Git"],
    image: "https://www.svgrepo.com/show/434372/testing.svg"
  },
  {
    id: 11,
    title: "Database Administrator",
    company: "Data Management Solutions",
    salary: "$90,000 - $125,000",
    location: "Houston, TX",
    jobType: "Full-time",
    category: "Database Administration",
    level: "Mid-Senior Level",
    description: "Become a Database Administrator and manage and optimize our organization's database systems for performance and reliability.",
    technicalSkills: ["SQL Server", "MySQL", "PostgreSQL", "Oracle DB", "Database Tuning", "Backup & Recovery"],
    image: "https://www.svgrepo.com/show/479866/cloud-database-12.svg"
  },
  {
    id: 12,
    title: "Network Engineer",
    company: "Connectivity Experts Inc.",
    salary: "$85,000 - $120,000",
    location: "Dallas, TX",
    jobType: "Full-time",
    category: "Networking",
    level: "Mid-Level",
    description: "Join us as a Network Engineer to design, implement, and maintain our company's network infrastructure and ensure optimal connectivity.",
    technicalSkills: ["Cisco", "Juniper", "TCP/IP", "Routing", "Switching", "Firewalls"],
    image: "https://www.svgrepo.com/show/479873/cloud-networking-07.svg"
  },
  {
    id: 13,
    title: "Technical Writer",
    company: "Clarity Communications",
    salary: "$75,000 - $100,000",
    location: "Raleigh, NC",
    jobType: "Full-time",
    category: "Technical Writing",
    level: "Mid-Level",
    description: "We are hiring a Technical Writer to create clear and concise documentation for our software products and APIs.",
    technicalSkills: ["Technical Documentation", "API Documentation", "User Manuals", "Markdown", "Confluence", "ReadMe.io"],
    image: "https://www.svgrepo.com/show/495531/technical-document.svg"
  },
  {
    id: 14,
    title: "IT Project Manager",
    company: "Project Dynamics Corp.",
    salary: "$95,000 - $135,000",
    location: "Orlando, FL",
    jobType: "Full-time",
    category: "Project Management",
    level: "Mid-Senior Level",
    description: "Become an IT Project Manager and lead and coordinate IT projects from initiation to closure, ensuring timely and within-budget delivery.",
    technicalSkills: ["Project Planning", "Agile", "Scrum", "Stakeholder Management", "Budgeting", "Risk Management"],
    image: "https://www.svgrepo.com/show/438314/project-management.svg"
  },
  {
    id: 15,
    title: "Business Intelligence Analyst",
    company: "Insightful Data Solutions",
    salary: "$80,000 - $115,000",
    location: "Phoenix, AZ",
    jobType: "Full-time",
    category: "Business Intelligence",
    level: "Mid-Level",
    description: "We are looking for a Business Intelligence Analyst to analyze business data, create reports and dashboards, and provide actionable insights.",
    technicalSkills: ["Data Analysis", "SQL", "Tableau", "Power BI", "Data Warehousing", "ETL"],
    image: "https://www.svgrepo.com/show/485797/business-intelligence.svg"
  },
  {
    id: 16,
    title: "UX Researcher",
    company: "User Experience Insights",
    salary: "$75,000 - $105,000",
    location: "San Diego, CA",
    jobType: "Full-time",
    category: "UX Research",
    level: "Mid-Level",
    description: "Join our team as a UX Researcher and conduct user research to understand user behaviors, needs, and pain points to improve product design.",
    technicalSkills: ["User Research", "Usability Testing", "User Interviews", "Surveys", "Data Analysis", "UX Design Principles"],
    image: "https://www.svgrepo.com/show/514575/user-research.svg"
  },
  {
    id: 17,
    title: "Sales Engineer",
    company: "Solution Sales Group",
    salary: "$90,000 - $150,000",
    location: "San Jose, CA",
    jobType: "Full-time",
    category: "Sales Engineering",
    level: "Mid-Senior Level",
    description: "Become a Sales Engineer and provide technical expertise to the sales process, demonstrating product capabilities and solutions to clients.",
    technicalSkills: ["Technical Sales", "Product Demonstrations", "Solution Architecture", "Presentation Skills", "CRM Software", "Technical Product Knowledge"],
    image: "https://www.svgrepo.com/show/454643/sales-call.svg"
  },
  {
    id: 18,
    title: "Product Manager",
    company: "Visionary Products Inc.",
    salary: "$110,000 - $160,000",
    location: "Seattle, WA",
    jobType: "Full-time",
    category: "Product Management",
    level: "Senior Level",
    description: "We are hiring a Product Manager to define and execute the product strategy, roadmap, and lifecycle for our innovative tech products.",
    technicalSkills: ["Product Strategy", "Roadmap Planning", "Market Research", "Agile Development", "User Stories", "Product Analytics"],
    image: "https://www.svgrepo.com/show/522424/product-management.svg"
  },
  {
    id: 19,
    title: "AR/VR Developer",
    company: "Immersive Experiences Ltd.",
    salary: "$95,000 - $130,000",
    location: "Los Angeles, CA",
    jobType: "Full-time",
    category: "AR/VR Development",
    level: "Mid-Level",
    description: "Join us as an AR/VR Developer and create immersive and interactive augmented and virtual reality experiences for various applications.",
    technicalSkills: ["Unity", "Unreal Engine", "C#", "C++", "ARKit", "VR SDKs"],
    image: "https://www.svgrepo.com/show/492725/augmented-reality-01.svg"
  },
  {
    id: 20,
    title: "Blockchain Developer",
    company: "Decentralized Innovations",
    salary: "$115,000 - $155,000",
    location: "New York, NY",
    jobType: "Full-time",
    category: "Blockchain Development",
    level: "Mid-Senior Level",
    description: "Become a Blockchain Developer and build decentralized applications and smart contracts using blockchain technologies.",
    technicalSkills: ["Solidity", "Ethereum", "Web3.js", "Blockchain Architecture", "Cryptography", "Smart Contracts"],
    image: "https://www.svgrepo.com/show/479861/blockchain-14.svg"
  },
  {
    id: 21,
    title: "Embedded Systems Engineer",
    company: "Embedded Logic Solutions",
    salary: "$90,000 - $125,000",
    location: "Detroit, MI",
    jobType: "Full-time",
    category: "Embedded Systems",
    level: "Mid-Level",
    description: "We are seeking an Embedded Systems Engineer to design, develop, and test embedded software and hardware for various devices and systems.",
    technicalSkills: ["C", "C++", "Microcontrollers", "Firmware Development", "RTOS", "Hardware Debugging"],
    image: "https://www.svgrepo.com/show/487784/electronics-06.svg"
  },
  {
    id: 22,
    title: "Robotics Engineer",
    company: "Automated Robotics Corp.",
    salary: "$100,000 - $140,000",
    location: "Pittsburgh, PA",
    jobType: "Full-time",
    category: "Robotics",
    level: "Mid-Senior Level",
    description: "Join our robotics team as a Robotics Engineer and develop and program robots and robotic systems for automation and innovation.",
    technicalSkills: ["ROS", "Python", "C++", "Robot Kinematics", "Sensors", "Actuators"],
    image: "https://www.svgrepo.com/show/438850/robotics.svg"
  },
  {
    id: 23,
    title: "Game Developer",
    company: "Interactive Gaming Studios",
    salary: "$85,000 - $120,000",
    location: "Austin, TX",
    jobType: "Full-time",
    category: "Game Development",
    level: "Mid-Level",
    description: "Become a Game Developer and create engaging and entertaining video games for various platforms, contributing to all stages of game development.",
    technicalSkills: ["Unity", "Unreal Engine", "C#", "C++", "Game Design", "Game Physics"],
    image: "https://www.svgrepo.com/show/433878/game-development.svg"
  },
  {
    id: 24,
    title: "Bioinformatics Analyst",
    company: "Genomic Data Insights",
    salary: "$95,000 - $130,000",
    location: "San Francisco, CA",
    jobType: "Full-time",
    category: "Bioinformatics",
    level: "Mid-Senior Level",
    description: "We are hiring a Bioinformatics Analyst to analyze biological data, develop bioinformatics tools, and contribute to genomic research.",
    technicalSkills: ["Python", "R", "Bioinformatics Tools", "Genomics", "Data Analysis", "NGS Data"],
    image: "https://www.svgrepo.com/show/485796/bioinformatics.svg"
  },
  {
    id: 25,
    title: "Financial Software Engineer",
    company: "FinTech Innovations Corp.",
    salary: "$110,000 - $150,000",
    location: "New York, NY",
    jobType: "Full-time",
    category: "FinTech",
    level: "Senior Level",
    description: "Join our FinTech team as a Financial Software Engineer and develop and maintain software solutions for the financial industry.",
    technicalSkills: ["Java", "Python", " 금융 공학", "Algorithm Design", " 금융 시장", "Trading Systems"], // Korean for Financial Engineering & Financial Market, assuming Fintech context can involve global teams.
    image: "https://www.svgrepo.com/show/490521/fintech.svg"
  },
  {
    id: 26,
    title: "EdTech Software Developer",
    company: "Educational Technologies Ltd.",
    salary: "$80,000 - $115,000",
    location: "Boston, MA",
    jobType: "Full-time",
    category: "EdTech",
    level: "Mid-Level",
    description: "Become an EdTech Software Developer and build innovative educational software and platforms to enhance learning experiences.",
    technicalSkills: ["JavaScript", "ReactJS", "Node.js", "LMS Platforms", "eLearning Standards", "UI/UX Design"],
    image: "https://www.svgrepo.com/show/488009/e-learning-online-education.svg"
  },
  {
    id: 27,
    title: "MarTech Analyst",
    company: "Marketing Analytics Group",
    salary: "$70,000 - $100,000",
    location: "Chicago, IL",
    jobType: "Full-time",
    category: "Marketing Technology",
    level: "Mid-Level",
    description: "We are seeking a MarTech Analyst to leverage marketing technologies to analyze campaign performance and optimize marketing strategies.",
    technicalSkills: ["Google Analytics", "Adobe Marketing Cloud", "CRM Software", "SEO/SEM", "Data Analysis", "Marketing Automation"],
    image: "https://www.svgrepo.com/show/517909/marketing-analytics.svg"
  },
  {
    id: 28,
    title: "HR Tech Specialist",
    company: "Human Resources Systems Inc.",
    salary: "$75,000 - $105,000",
    location: "Atlanta, GA",
    jobType: "Full-time",
    category: "HR Technology",
    level: "Mid-Level",
    description: "Join our team as an HR Tech Specialist and implement and manage HR technology solutions to streamline HR processes and improve efficiency.",
    technicalSkills: ["HRIS Systems", "HCM Software", "Applicant Tracking Systems", "Payroll Systems", "Data Analysis", "Process Automation"],
    image: "https://www.svgrepo.com/show/491307/hr-human-resource.svg"
  },
  {
    id: 29,
    title: "Legal Tech Developer",
    company: "Legal Innovation Technologies",
    salary: "$90,000 - $125,000",
    location: "Washington, D.C.",
    jobType: "Full-time",
    category: "Legal Technology",
    level: "Mid-Level",
    description: "Become a Legal Tech Developer and create software solutions for the legal industry, including case management and legal research tools.",
    technicalSkills: ["Python", "Java", "Database Management", "Legal Research Platforms", "Document Management Systems", "Workflow Automation"],
    image: "https://www.svgrepo.com/show/491953/law-scale.svg"
  },
  {
    id: 30,
    title: "IT Support Specialist",
    company: "Technical Assistance Group",
    salary: "$60,000 - $80,000",
    location: "Miami, FL",
    jobType: "Full-time",
    category: "IT Support",
    level: "Entry-Mid Level",
    description: "We are looking for an IT Support Specialist to provide technical support to end-users, troubleshoot hardware and software issues, and maintain IT infrastructure.",
    technicalSkills: ["Technical Support", "Troubleshooting", "Hardware Maintenance", "Software Installation", "Networking Basics", "Help Desk Software"],
    image: "https://www.svgrepo.com/show/491688/information-technology.svg"
  }
];

export default { jobs };
